name: jake-blog-content-push

on:
  push:
    branches: [ "main" ]

jobs:
  push-update:
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IDP_ARN }}
          aws-region: us-east-1

      - name: Sync images to S3
        run: |
          aws s3 sync images/ s3://jakeblog-blog-image-cache/ --delete

      - name: Dispatch update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: jacob-alan-henning/jake-blog
          event-type: blog-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

